# Site settings
title: "COMPSCI 682 Neural Networks: A Modern Introduction"
# email: umass.deep.learning+682@gmail.com
description: "Course Materials and Notes for UMass-Amherst COMPSCI 682 Neural Networks: A Modern Introduction."
url: https://cvl-umass.github.io # the base hostname & protocol for your site
baseurl: /compsci682-fall-2024 # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
